### ISSUE TITLE
ConnectionTimeout issues when exporting data from highly accessed ES

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#68]
It does not happen systematically (probably only during episodes of high frequency writing of tweets within the index), but sometimes when running `gazou export` on a big corpus (45M tweets indexed and 3M more by day), we encounter the following stack:

```
Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/boo/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/boo/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/boo/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/boo/.pyenv/versions/3.8.7/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 245, in perform_request
    response = self.pool.urlopen(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/util/retry.py", line 506, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/gazou/bin/gazou", line 8, in <module>
    sys.exit(main())
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/gazouilloire/cli/__main__.py", line 129, in export
    export_csv(conf, query, exclude_threads, verbose, export_threads_from_file, columns, output)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/gazouilloire/exports/export_csv.py", line 126, in export_csv
    for t in iterator:
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/progressbar/bar.py", line 547, in __next__
    value = next(self._iterable)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/gazouilloire/exports/export_csv.py", line 12, in yield_csv
    for t in queryiterator:
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 524, in scan
    resp = client.search(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1658, in search
    return self.transport.perform_request(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
```

**Comment by Yomguithereal** [comment]
The python ES client docs is pretty hazy but it seems we can get away with it with a combination of `retry_on_timeout` and `timeout=30` as kwargs as proposed by the above commit?

**Comment by boogheta** [comment]
sounds fair, would need to try it on our charge test corpus, which supposes to release and upgrade gazouilloire there I guess, so I'll let @bmaz proceeed before testing again a bit later, thanks
