### ISSUE TITLE
Gazou count crashes with _csv.Error

### ISSUE THREAD

**Issue by boogheta** [medialab/gazouilloire#88]
```gazou count  '{"links_to_resolve": True}'```

=>

```
Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/gazou/bin/gazou", line 8, in <module>
    sys.exit(main())
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/gazouilloire/cli/__main__.py", line 185, in count
    count_by_step(conf, query, exclude_threads, exclude_retweets, since, until, output, step)
  File "/home/boo/.pyenv/versions/3.8.7/envs/gazou/lib/python3.8/site-packages/gazouilloire/exports/export_csv.py", line 188, in count_by_step
    writer.writerow([",".join(query), count])
_csv.Error: need to escape, but no escapechar set
```

**Comment by boogheta** [comment]
```gazou count  "{'links_to_resolve': True}"``` does work

**Comment by Yomguithereal** [comment]
The culprit :) https://github.com/medialab/gazouilloire/blob/elasticPy3-merge/gazouilloire/exports/export_csv.py#L169
